public class A3SH_StagesApiRequestDetailBean {
    
    public string site_name {get;set;}
    public string address {get;set;}
    public string address2 {get;set;}
    public string city {get;set;}
    public string state {get;set;}
    public string zip_code {get;set;}
    public string billing_id {get;set;}
    public string phone_number {get;set;}
    public string email_address {get;set;}
    public string type {get;set;}
    Public string system_id {get;set;}
    Public string item_code {get;set;}
    Public string first_name {get;set;}
    Public string last_name {get;set;}

}