name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: auth with sfdx
      shell: bash
      run: 'echo ${{secrets.DEV_AUTH_URL}} > SFDX_DEV'
    
